"""The fixture / current-publication boundary (WO-010-R1 §1, §6, §8, §9, §10).

WO-010 shipped a working analysis engine driven entirely by labelled fixtures.
Every number on the Dashboard was generated by this repository, and nothing in
the data model recorded that fact in a way the code could act on. These tests
pin the boundary that fixes it: a fixture may exercise the engine, and it may
never appear as current Logistics intelligence.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from analysis.provenance import (  # noqa: E402
    CURRENT_PUBLICATION,
    FIXTURE_ORIGINS,
    HISTORICAL_VALIDATION,
    LIVE_FRESHNESS_STATUSES,
    SYNTHETIC_SOURCE_ID,
    TECHNICAL_DEMO,
    effective_source_id,
    fixture_freshness_status,
    is_fixture,
    provenance_problems,
    qualifies_for_current_publication,
    record_intended_source_id,
    record_origin,
    record_source_id,
)
from scripts.build_dashboard import build_payloads  # noqa: E402
from scripts.validate import source_contract_checks  # noqa: E402

PUBLIC = ROOT / "dashboard" / "public"
OBSERVATION_FAMILIES = (
    "indicator_observations",
    "trade_observations",
    "port_observations",
    "cost_observations",
)


def _load(relative: str):
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def payloads():
    return build_payloads()


@pytest.fixture(scope="module")
def registry():
    return yaml.safe_load((ROOT / "config/sources.yaml").read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def observations():
    return {
        family: _load(f"data/observations/{family}.json")["records"]
        for family in OBSERVATION_FAMILIES
    }


# ---------------------------------------------------------------------------
# §1 / §6: every record says what it is and where it came from
# ---------------------------------------------------------------------------


def test_every_observation_declares_a_recognised_origin(observations):
    for family, records in observations.items():
        for record in records:
            origin = record_origin(record)
            assert origin is not None, f"{family}: a record carries no evidence_origin"
            assert not provenance_problems(record, label=family)


def test_the_whole_observation_set_is_currently_fixture_backed(observations, registry):
    """Stated as a test so the day a real source is enabled, this fails and
    forces every current-publication expectation below to be revisited."""
    origins = {record_origin(record) for records in observations.values() for record in records}
    assert origins <= FIXTURE_ORIGINS
    assert not any(
        qualifies_for_current_publication(record, registry=registry)
        for records in observations.values()
        for record in records
    )


def test_no_fixture_is_attributed_to_a_real_publisher(observations):
    for family, records in observations.items():
        for record in records:
            if not is_fixture(record_origin(record)):
                continue
            assert record_source_id(record) == SYNTHETIC_SOURCE_ID, family
            assert record_intended_source_id(record), family


def test_no_fixture_carries_a_retrieval_timestamp(observations):
    for records in observations.values():
        for record in records:
            provenance = record["provenance"]
            assert provenance["retrieval_status"] == "not_retrieved"
            assert provenance["retrieved_at"] is None
            assert provenance["fixture_created_at"]


def test_every_intended_source_is_a_real_registry_entry(observations, registry):
    registry_ids = {source["id"] for source in registry["sources"]}
    for records in observations.values():
        for record in records:
            intended = record_intended_source_id(record)
            if intended:
                assert intended in registry_ids, intended


#: The corrected series-to-source map. WO-010 attributed the freight benchmark
#: and Brent to the fuel publisher, and FX and LSCI to the supply-chain index,
#: because the mapping lived in a hard-coded table beside the series names
#: rather than in each record's provenance.
EXPECTED_INTENDED_SOURCE = {
    "usd_thb_reference_rate": "BOT_FX",
    "thailand_lsci": "UNCTAD_MARITIME",
    "gscpi_index": "GSCPI",
    "brent_crude_price": "WB_COMMODITY",
    "thailand_diesel_retail_price": "EPPO_FUEL",
    "container_freight_benchmark": "FBX_PUBLIC",
    "thailand_port_calls": "IMF_PORTWATCH",
    "laem_chabang_container_throughput": "PAT_STATISTICS",
    "bangkok_port_container_throughput": "PAT_STATISTICS",
}

FORBIDDEN_MAPPINGS = {
    ("container_freight_benchmark", "EPPO_FUEL"),
    ("brent_crude_price", "EPPO_FUEL"),
    ("usd_thb_reference_rate", "GSCPI"),
    ("thailand_lsci", "GSCPI"),
    ("laem_chabang_container_throughput", "IMF_PORTWATCH"),
    ("bangkok_port_container_throughput", "IMF_PORTWATCH"),
}


@pytest.mark.parametrize("series_id,expected", sorted(EXPECTED_INTENDED_SOURCE.items()))
def test_each_series_stands_in_for_the_right_production_candidate(
    observations, series_id, expected
):
    records = [
        record
        for family in OBSERVATION_FAMILIES
        for record in observations[family]
        if (record.get("series_id") or record.get("indicator_id")) == series_id
    ]
    assert records, series_id
    assert {record_intended_source_id(record) for record in records} == {expected}


def test_trade_series_stand_in_for_thai_customs(observations):
    trade = observations["trade_observations"]
    assert trade
    assert {record_intended_source_id(record) for record in trade} == {"TH_CUSTOMS"}


@pytest.mark.parametrize("series_id,forbidden", sorted(FORBIDDEN_MAPPINGS))
def test_the_wo_010_mis_attributions_are_gone(observations, series_id, forbidden):
    """Each pair here is a mapping WO-010 actually made, or one the Work Order
    names as forbidden. Official TEU throughput in particular is not a
    PortWatch estimate and must not be attributed to one."""
    records = [
        record
        for family in OBSERVATION_FAMILIES
        for record in observations[family]
        if (record.get("series_id") or record.get("indicator_id")) == series_id
    ]
    assert records, series_id
    assert forbidden not in {record_intended_source_id(record) for record in records}


def test_effective_source_resolves_a_fixture_to_its_production_candidate(observations):
    record = observations["cost_observations"][0]
    assert record_source_id(record) == SYNTHETIC_SOURCE_ID
    assert effective_source_id(record) == record_intended_source_id(record)


def test_the_dashboard_derives_source_identity_from_provenance_not_a_lookup_table():
    """The hard-coded ``_SOURCE_BY_SERIES`` table is what let a series name and
    a publisher drift apart. It must not come back."""
    source = (ROOT / "scripts" / "build_dashboard.py").read_text(encoding="utf-8")
    assert "_SOURCE_BY_SERIES" not in source


# ---------------------------------------------------------------------------
# §7: the freight benchmark has a real disposition
# ---------------------------------------------------------------------------


def test_a_freight_benchmark_candidate_exists_and_is_not_the_fuel_publisher(registry):
    sources = {source["id"]: source for source in registry["sources"]}
    assert "FBX_PUBLIC" in sources
    benchmark = sources["FBX_PUBLIC"]
    assert benchmark["enabled"] is False
    assert benchmark["enablement"]["blockers"]
    roles = benchmark["qualification"]["logistics_role"]
    assert "freight_market_benchmark_or_proxy" in roles
    assert (
        "freight_market_benchmark_or_proxy"
        not in (sources["EPPO_FUEL"]["qualification"]["logistics_role"])
    )


def test_the_freight_benchmark_never_claims_to_be_a_thailand_rate(payloads):
    series = [
        item
        for item in payloads["cost.json"]["cost_series"]
        if item["series_id"] == "container_freight_benchmark"
    ]
    assert series
    assert series[0]["quotation_claim"] == "not_a_quotation"
    assert series[0]["benchmark_class"] != "actual_quotation"
    assert series[0]["applies_to_thailand"] != "direct"


# ---------------------------------------------------------------------------
# §8: the enablement gate
# ---------------------------------------------------------------------------


def test_no_source_is_enabled(registry):
    assert [source["id"] for source in registry["sources"] if source["enabled"]] == []


def test_tmd_and_gdacs_remain_disabled(registry):
    sources = {source["id"]: source for source in registry["sources"]}
    for source_id in ("TMD_CAP", "GDACS"):
        assert source_id in sources
        assert sources[source_id]["enabled"] is False


def _enabled_candidate(**qualification_overrides):
    """A source that would pass every gate, for one-field negative tests."""
    return {
        "version": "0.8",
        "last_reviewed_at": "2026-07-24",
        "policy": "free_sources_only",
        "sources": [
            {
                "id": "CANDIDATE",
                "name": "Candidate",
                "owner": "Someone",
                "source_class": "official",
                "landing_url": "https://example.org",
                "endpoint": "https://example.org/data.csv",
                "access_method": "http_get",
                "format": "csv",
                "machine_readable_status": "verified",
                "licence_status": "reviewed",
                "enabled": True,
                "required_for_publication": False,
                "known_limitations": ["x"],
                "qualification": {
                    "access_cost": "free",
                    "paywall_status": "none",
                    "reuse_status": "permitted_with_attribution",
                    "redistribution_status": "derived_only",
                    "prototype_eligibility": "eligible",
                    "observed_freshness": "2026-07-20",
                    "publication_cadence": "monthly",
                    "logistics_role": ["thailand_trade_flow"],
                    **qualification_overrides,
                },
                "enablement": {
                    "live_validation_status": "completed",
                    "live_validation_reference": "docs/source_enablement_decisions.md",
                    "fixture_test_exists": True,
                    "fixture_test_reference": "tests/test_csv_series_adapter.py",
                    "parser_fails_closed": True,
                    "response_bounded": True,
                    "schedule_justified": True,
                    "public_repository_safe": True,
                    "blockers": [],
                },
            }
        ],
    }


def test_the_gate_accepts_a_fully_qualified_candidate():
    assert source_contract_checks(_enabled_candidate()) == []


@pytest.mark.parametrize(
    "override,expected",
    [
        ({"access_cost": "paid"}, "free-only policy"),
        ({"access_cost": "unknown"}, "free or free-with-registration"),
        ({"paywall_status": "full"}, "fully paywalled"),
        ({"reuse_status": "unknown"}, "reviewed reuse position"),
        ({"reuse_status": "restricted"}, "reviewed reuse position"),
        ({"redistribution_status": "prohibited"}, "redistribution"),
        ({"prototype_eligibility": "conditional"}, "prototype_eligibility"),
        ({"observed_freshness": None}, "independently observed"),
        ({"publication_cadence": None}, "cadence"),
    ],
)
def test_a_single_unmet_qualification_gate_blocks_enablement(override, expected):
    problems = source_contract_checks(_enabled_candidate(**override))
    assert any(expected in problem for problem in problems), problems


@pytest.mark.parametrize(
    "override,expected",
    [
        ({"blockers": ["endpoint unverified"]}, "unresolved enablement"),
        ({"fixture_test_exists": False}, "fixture test"),
        ({"fixture_test_reference": None}, "fixture test reference"),
        ({"live_validation_status": "not_required"}, "genuinely manual"),
        ({"live_validation_status": "pending"}, "controlled live validation"),
        ({"live_validation_reference": None}, "evidence reference"),
        ({"parser_fails_closed": False}, "fail-closed parser"),
        ({"response_bounded": False}, "bounded response"),
        ({"schedule_justified": False}, "justified collection schedule"),
        ({"public_repository_safe": False}, "public repository"),
    ],
)
def test_a_single_unmet_enablement_gate_blocks_enablement(override, expected):
    registry = _enabled_candidate()
    registry["sources"][0]["enablement"].update(override)
    problems = source_contract_checks(registry)
    assert any(expected in problem for problem in problems), problems


def test_not_required_live_validation_is_allowed_for_a_manual_contract():
    registry = _enabled_candidate()
    registry["sources"][0]["access_method"] = "manual"
    registry["sources"][0]["enablement"]["live_validation_status"] = "not_required"
    registry["sources"][0]["enablement"]["live_validation_reference"] = None
    assert source_contract_checks(registry) == []


# ---------------------------------------------------------------------------
# §9: fixture freshness is disjoint from real-world freshness
# ---------------------------------------------------------------------------


def test_a_fixture_never_receives_a_real_world_freshness_label():
    for origin in FIXTURE_ORIGINS:
        assert fixture_freshness_status(origin) not in LIVE_FRESHNESS_STATUSES
    assert fixture_freshness_status("synthetic_test_fixture") == "fixture_not_live"
    assert fixture_freshness_status("historical_validation_fixture") == "historical_validation"
    assert fixture_freshness_status("live_retrieved") == "not_applicable"


def test_every_demo_series_reports_fixture_freshness(payloads):
    series = [
        *payloads["cost.json"]["cost_series"],
        payloads["cost.json"]["fx"],
        *payloads["ocean.json"]["demo_port_series"],
        *(flow for lane in payloads["trade.json"]["lane_flows"] for flow in lane["flows"]),
    ]
    assert series
    for item in series:
        assert item["freshness"]["status"] == "fixture_not_live", item.get("series_id")


def test_no_current_domain_assessment_claims_real_world_freshness(payloads):
    for lane in payloads["ocean.json"]["lanes"]:
        for domain in lane["assessment"]["domain_assessments"]:
            assert domain["freshness"]["status"] == "no_data"


# ---------------------------------------------------------------------------
# §1 / §10: the current view holds nothing fixture-derived
# ---------------------------------------------------------------------------


def test_the_current_thailand_view_is_insufficient_across_the_board(payloads):
    situation = payloads["thailand_situation.json"]
    assert situation["dataset"] == CURRENT_PUBLICATION
    assert situation["overall_direction"] == "insufficient_evidence"
    assert situation["evidence_coverage"] == "insufficient"
    assert situation["active_verified_events"] == []
    assert situation["lanes_requiring_attention"] == []
    assert situation["qualified_observation_count"] == 0
    assert situation["qualified_event_count"] == 0


def test_no_lane_is_raised_above_routine_in_the_current_view(payloads):
    for lane in payloads["ocean.json"]["lanes"]:
        assessment = lane["assessment"]
        assert assessment["dataset"] == CURRENT_PUBLICATION
        assert assessment["attention_level"] == "insufficient_evidence"
        assert assessment["overall_direction"] == "insufficient_evidence"
        assert assessment["active_event_ids"] == []


def test_the_demo_assessments_still_exercise_the_engine(payloads):
    """The demonstration must remain a real demonstration: if every demo lane
    also came out 'insufficient', the separation would be untested."""
    demo = [lane["demo_assessment"] for lane in payloads["ocean.json"]["lanes"]]
    assert all(item is not None for item in demo)
    assert all(item["dataset"] == TECHNICAL_DEMO for item in demo)
    assert any(item["attention_level"] in {"watch", "elevated"} for item in demo)


def test_no_chokepoint_is_labelled_as_having_an_active_notice(payloads):
    for lane in payloads["ocean.json"]["lanes"]:
        for exposure in lane["assessment"]["chokepoint_exposure"]:
            assert exposure["status"] != "official_notice_active"
    assert payloads["ocean.json"]["current_operational_notices"] == []
    assert payloads["ocean.json"]["current_capacity_and_service_evidence"] == []


def test_no_current_event_is_published(payloads):
    events = payloads["events.json"]
    assert events["dataset"] == CURRENT_PUBLICATION
    assert events["current_direct_operational_events"] == []
    assert events["current_external_drivers"] == []
    # The historical cases are still there, in their own labelled group.
    assert events["demo_direct_operational_events"]


def test_every_historical_event_carries_its_assessment_cutoff(payloads):
    demo = payloads["events.json"]["demo_direct_operational_events"]
    assert demo
    for event in demo:
        assert event["dataset"] == HISTORICAL_VALIDATION
        assert event["assessment_cutoff"], event["event_id"]
        assert event["case_id"], event["event_id"]
        assert event["active_as_of"] is None


def test_current_scenarios_state_only_what_coverage_is_missing(payloads):
    outlooks = payloads["ai_outlook.json"]["current_outlooks"]
    assert len(outlooks) == 11
    for entry in outlooks:
        assert entry["attention_level"] == "insufficient_evidence"
        base = entry["scenarios"]["base_case"]
        assert base["trigger_conditions"], entry["lane_id"]
        assert base["data_gaps"], entry["lane_id"]


def test_evidence_records_separate_expected_strength_from_verified_strength(payloads):
    items = [
        item
        for event in payloads["events.json"]["demo_direct_operational_events"]
        for item in event["evidence"]
    ]
    assert items
    for item in items:
        assert item["strength_basis"] == "expected_at_cutoff"
        assert item["retrieval_status"] == "not_retrieved"
        assert item["retrieved_at"] is None
        assert item["intended_source_id"]


# ---------------------------------------------------------------------------
# Air foundation — WO-039
# ---------------------------------------------------------------------------


def test_no_air_lane_carries_a_current_assessment(payloads):
    for lane in payloads["air.json"]["lanes"]:
        assert lane["assessment"] is None
        assert "insufficient_evidence" in lane["assessment_note"]
        assert "coverage gap" in lane["assessment_note"]


def test_the_air_section_states_insufficient_live_coverage(payloads):
    air = payloads["air.json"]
    assert air["live_coverage"] == "insufficient"
    assert air["module_status"] == "planned"
    assert "INSUFFICIENT" in air["live_coverage_statement"]
    assert "coverage gap, not a finding" in air["coverage_message"]
    gaps = " ".join(air["source_gaps"]).lower()
    # A truthy-only check here would pass even if the two headline gaps this
    # module stands on -- the unresolved air-freight-pass licence and the
    # missing Thailand air freight rate benchmark -- were silently dropped.
    assert "unresolved licence" in gaps
    assert "air freight rate benchmark" in gaps


def test_no_air_record_enters_the_current_publication_surface(payloads):
    for event in payloads["air.json"]["historical_air_events"]:
        assert event["dataset"] == HISTORICAL_VALIDATION
    assert payloads["events.json"]["current_direct_operational_events"] == []
    assert all(lane["mode"] != "air" for lane in payloads["ocean.json"]["lanes"])


# ---------------------------------------------------------------------------
# Land foundation (Road, Rail, Border) — WO-041
# ---------------------------------------------------------------------------


def test_no_land_lane_carries_a_current_assessment(payloads):
    for lane in payloads["land.json"]["lanes"]:
        assert lane["assessment"] is None
        assert "insufficient_evidence" in lane["assessment_note"]
        assert "coverage gap" in lane["assessment_note"]


def test_the_land_section_states_insufficient_live_coverage(payloads):
    land = payloads["land.json"]
    assert land["live_coverage"] == "insufficient"
    assert land["module_status"] == {"road": "planned", "rail": "planned", "border": "planned"}
    assert "INSUFFICIENT" in land["live_coverage_statement"]
    assert "coverage gap, not a finding" in land["coverage_message"]
    gaps = " ".join(land["source_gaps"]).lower()
    # A truthy-only check here would pass even if the headline gaps this
    # module stands on were silently dropped -- see PR #78's fix for the
    # equivalent Air oversight.
    assert "unresolved licence" in gaps
    assert "no dataset of any kind" in gaps
    assert "cross-cutting" in gaps


def test_no_land_record_enters_the_current_publication_surface(payloads):
    for event in payloads["land.json"]["historical_land_events"]:
        assert event["dataset"] == HISTORICAL_VALIDATION
    assert payloads["events.json"]["current_direct_operational_events"] == []
    assert all(
        lane["mode"] not in {"road", "rail", "border"} for lane in payloads["ocean.json"]["lanes"]
    )
    assert all(
        lane["mode"] not in {"road", "rail", "border"} for lane in payloads["air.json"]["lanes"]
    )


def test_the_ocean_and_air_payloads_are_unchanged_in_size_by_the_land_foundation(payloads):
    assert len(payloads["ocean.json"]["lanes"]) == 11
    assert len(payloads["air.json"]["lanes"]) == 5
    assert len(payloads["ai_outlook.json"]["current_outlooks"]) == 11


def test_the_ocean_payload_is_unchanged_in_size_by_the_air_foundation(payloads):
    assert len(payloads["ocean.json"]["lanes"]) == 11
    assert len(payloads["ai_outlook.json"]["current_outlooks"]) == 11


# ---------------------------------------------------------------------------
# §10: the label is on every panel, not only the page banner
# ---------------------------------------------------------------------------


def test_the_page_declares_a_current_and_a_demonstration_region_for_each_topic():
    html = (PUBLIC / "index.html").read_text(encoding="utf-8")
    for current_id, demo_id in (
        ("situation-cost-current", "situation-cost-table"),
        ("current-notice-statement", "notices"),
        ("trade-current", "trade-demo-label"),
        ("cost-current", "cost-demo-label"),
        ("events-current-statement", "events-demo-label"),
        ("current-outlooks", "outlook-demo-label"),
    ):
        assert f'id="{current_id}"' in html, current_id
        assert f'id="{demo_id}"' in html, demo_id


def test_every_demonstration_heading_carries_its_own_marker():
    """A page-level banner is not enough: a reader who deep-links to a section
    or prints one panel must still see that it is a demonstration."""
    html = (PUBLIC / "index.html").read_text(encoding="utf-8")
    headings = re.findall(r'<h3 class="demo-heading">(.*?)</h3>', html, re.S)
    assert len(headings) >= 6
    for heading in headings:
        assert "pill-demo" in heading, heading


def test_the_renderer_labels_each_fixture_backed_panel_individually():
    script = (PUBLIC / "assets" / "app.js").read_text(encoding="utf-8")
    assert "DEMO_LABEL" in script
    assert "demoTag(" in script
    # Series blocks, event cards, outlook blocks and the in-card lane panel.
    assert script.count("data-demo-label") >= 4
    assert "demo-panel" in script


def test_fixture_freshness_statuses_are_styled_as_demonstration_not_as_fresh():
    script = (PUBLIC / "assets" / "app.js").read_text(encoding="utf-8")
    pills = script.split("var FRESHNESS_PILL", 1)[1].split("};", 1)[0]
    for status in ("fixture_not_live", "historical_validation", "not_applicable"):
        assert status in pills, status
    assert "fixture_not_live: 'pill-demo'" in pills


# ---------------------------------------------------------------------------
# WO-045: Ocean Dashboard Simplification -- evidence-first first screen
# ---------------------------------------------------------------------------


def _html() -> str:
    return (PUBLIC / "index.html").read_text(encoding="utf-8")


def _js() -> str:
    return (PUBLIC / "assets" / "app.js").read_text(encoding="utf-8")


def _js_function_body(js_text: str, name: str) -> str:
    """Balanced-brace body of a named top-level function, or '' if absent."""
    match = re.search(r"function\s+" + re.escape(name) + r"\s*\([^)]*\)\s*\{", js_text)
    if not match:
        return ""
    depth = 1
    i = match.end()
    while depth > 0 and i < len(js_text):
        if js_text[i] == "{":
            depth += 1
        elif js_text[i] == "}":
            depth -= 1
        i += 1
    return js_text[match.end() : i - 1]


def _ocean_section_html() -> str:
    match = re.search(r'<section id="ocean".*?</section>', _html(), re.S)
    assert match, "expected to find the #ocean section in index.html"
    return match.group(0)


def test_the_ocean_first_screen_cannot_imply_an_all_clear(payloads):
    """Issue #85's required top-of-page statement, used verbatim, plus a
    denylist scan: no reassurance phrase may appear anywhere in the Ocean
    section or its tier B/C renderers, and the one phrase the approved copy
    itself legitimately uses ("...not an all-clear") may only ever appear
    negated the same way."""
    section = _ocean_section_html()
    normalized = re.sub(r"\s+", " ", section)

    assert (
        "Current Thailand Ocean conditions cannot be assessed reliably because no "
        "qualified live source is enabled." in normalized
    )
    assert "This is a coverage gap, not an all-clear." in normalized
    assert 'id="ocean-headline"' in section

    for match in re.finditer(r"all[- ]clear", normalized, re.I):
        preceding = normalized[max(0, match.start() - 12) : match.start()].lower()
        assert "not an " in preceding, (
            f"unguarded 'all-clear' phrase: "
            f"...{normalized[max(0, match.start() - 40) : match.start() + 20]}..."
        )

    banned_phrases = (
        "no issues",
        "operating normally",
        "normal conditions",
        "no disruption",
        "no delays",
        "running smoothly",
        "everything is fine",
        "conditions are good",
    )
    lowered = normalized.lower()
    for phrase in banned_phrases:
        assert phrase not in lowered, f"banned reassurance phrase found in #ocean: {phrase!r}"

    script = _js()
    for name in ("oceanEvidenceCards", "oceanMajorGapItem", "renderOcean"):
        body = _js_function_body(script, name)
        assert body, f"expected to resolve {name}'s body"
        body_lower = body.lower()
        for phrase in banned_phrases:
            assert phrase not in body_lower, f"{name} may construct banned phrase {phrase!r}"

    summary = payloads["ocean.json"]["evidence_summary"]
    assert summary["assessable"] is False
    assert payloads["thailand_situation.json"]["evidence_coverage"] == "insufficient"


def test_no_demonstration_value_reaches_the_ocean_first_screen(payloads):
    """Payload half: every evidence_summary value is reproducible from
    current_* fields alone. Renderer half: the tier B/C renderers reference
    no demo-only symbol. Builder half: the build-script helper that
    constructs evidence_summary touches no demo/TECHNICAL_DEMO/
    HISTORICAL_VALIDATION symbol, and specifically never reads the
    platform-wide qualified_event_count -- verified_current_event_count is
    Ocean-scoped, counted from Ocean's own current lists."""
    ocean = payloads["ocean.json"]
    summary = ocean["evidence_summary"]

    dated = (
        [s["current_period"] for s in ocean["current_port_series"] if s.get("current_period")]
        + [
            n["publication_date"]
            for n in ocean["current_operational_notices"]
            if n.get("publication_date")
        ]
        + [
            c["active_as_of"]
            for c in ocean["current_capacity_and_service_evidence"]
            if c.get("active_as_of")
        ]
    )
    assert summary["latest_evidence_date"] == (max(dated) if dated else None)

    expected_events = {n["event_id"] for n in ocean["current_operational_notices"]} | {
        c["event_id"] for c in ocean["current_capacity_and_service_evidence"]
    }
    assert summary["verified_current_event_count"] == len(expected_events)

    script = _js()
    forbidden_symbols = (
        "demo_assessment",
        "demo_port_series",
        "demo_operational_notices",
        "demo_capacity_and_service_evidence",
        "demo_label",
        "laneDemoBlock(",
        "DEMO_LABEL",
    )
    for name in ("oceanEvidenceCards", "oceanMajorGapItem"):
        body = _js_function_body(script, name)
        assert body, f"expected to resolve {name}'s body"
        for symbol in forbidden_symbols:
            assert symbol not in body, f"{name} references demo-only symbol {symbol!r}"

    build_src = (ROOT / "scripts" / "build_dashboard.py").read_text(encoding="utf-8")
    helper_match = re.search(
        r"def _ocean_evidence_summary\(.*?\n\ndef _ocean_major_gaps\(", build_src, re.S
    )
    assert helper_match, "expected to resolve _ocean_evidence_summary's source"
    helper_src = helper_match.group(0)
    for symbol in (
        "TECHNICAL_DEMO",
        "HISTORICAL_VALIDATION",
        "demo_assessment",
        "qualified_event_count",
    ):
        assert symbol not in helper_src, (
            f"_ocean_evidence_summary references {symbol!r} -- it must derive only from Ocean's "
            "own current_* fields, never a demo/historical symbol or the platform-wide count"
        )


def test_the_ocean_summary_never_renders_a_missing_value_as_zero(payloads):
    ocean = payloads["ocean.json"]
    assert ocean["evidence_summary"]["latest_evidence_date"] is None

    script = _js()
    cards_body = _js_function_body(script, "oceanEvidenceCards")
    assert cards_body, "expected to resolve oceanEvidenceCards's body"
    for banned in ("|| 0", "|| '0'", "Number(summary", "?? 0"):
        assert banned not in cards_body, (
            f"oceanEvidenceCards must not default a missing value to zero: {banned!r}"
        )

    assert "Not available" in cards_body
    assert '<span class="missing">' in cards_body
    assert "not that nothing is happening" in cards_body


def test_no_singapore_context_renders_as_thailand_ocean_evidence(payloads):
    ocean = payloads["ocean.json"]
    asean_lane = next(
        lane for lane in ocean["lanes"] if lane["lane_id"] == "LANE-OCEAN-TH-ASEAN-SG"
    )
    assert asean_lane["resolution"] == "regional"
    assert any(
        "transship" in limitation.lower() for limitation in asean_lane["known_limitations"]
    ), "expected the ASEAN/Singapore lane to retain its transshipment-attribution limitation"

    first_screen_payload = json.dumps(
        {
            "evidence_summary": ocean["evidence_summary"],
            "major_gaps": ocean["major_gaps"],
            "what_would_change_this": ocean["what_would_change_this"],
        }
    )
    assert "Singapore" not in first_screen_payload

    registry = yaml.safe_load((ROOT / "config/sources.yaml").read_text(encoding="utf-8"))
    mpa_notice = next(source for source in registry["sources"] if source["id"] == "MPA_SG_NOTICE")
    assert mpa_notice["enabled"] is False
    assert all(
        notice.get("source_id") != "MPA_SG_NOTICE"
        for notice in ocean["current_operational_notices"]
    )


def test_every_major_gap_traces_to_a_recorded_basis(payloads):
    ocean = payloads["ocean.json"]
    known_gaps_doc = (ROOT / "docs" / "known_data_gaps.md").read_text(encoding="utf-8")
    assert 4 <= len(ocean["major_gaps"]) <= 6

    for gap in ocean["major_gaps"]:
        assert gap["basis"].startswith("docs/known_data_gaps.md"), gap["gap_id"]
        match = re.search(r"\(([^)]+)\)$", gap["basis"])
        assert match, f"{gap['gap_id']}'s basis has no (row name): {gap['basis']!r}"
        row_name = match.group(1)
        assert f"**{row_name}**" in known_gaps_doc, (
            f"gap {gap['gap_id']!r}'s basis cites a row not present in "
            f"known_data_gaps.md: {row_name!r}"
        )
        assert gap["derived_from"], f"{gap['gap_id']} must declare how its membership was decided"


def test_truck_turnaround_gap_states_absence_of_source_only(payloads):
    """Issue #85 deviation D-2: this gap has the weakest evidence chain of
    the six, so its copy must say only that no source is registered --
    never that a delay exists, and never that one doesn't."""
    ocean = payloads["ocean.json"]
    gap = next(
        g for g in ocean["major_gaps"] if g["gap_id"] == "truck_turnaround_and_container_dwell"
    )
    text = (gap["headline"] + " " + gap["explanation"]).lower()
    assert "no truck-turnaround or container-dwell source is registered" in text
    assert "can be stated or ruled out" in text
    for banned in ("delays are", "trucks wait", "containers sit for", "average dwell time is"):
        assert banned not in text


def test_card_four_uses_the_ratified_capabilities_label():
    """Copy amendment 1 (ratified on Issue #85): card 4's label."""
    script = _js()
    body = _js_function_body(script, "oceanEvidenceCards")
    assert body, "expected to resolve oceanEvidenceCards's body"
    assert "Thailand-relevant current capabilities" in body


def test_what_would_change_this_names_more_than_licence_resolution(payloads):
    """Copy amendment 2 (ratified on Issue #85): the closing sentence must
    not present licence resolution as the only remaining source-specific
    check -- some candidates also carry their own unit/freshness/metadata
    checks, and the copy must say so."""
    text = payloads["ocean.json"]["what_would_change_this"]
    assert "unresolved licence and publication gap" in text
    assert "source-specific unit, freshness or metadata checks" in text
    assert "another qualified Thailand source meets the same conditions" in text
