"""The fixture / current-publication boundary (WO-010-R1 §1, §6, §8, §9, §10).

WO-010 shipped a working analysis engine driven entirely by labelled fixtures.
Every number on the Dashboard was generated by this repository, and nothing in
the data model recorded that fact in a way the code could act on. These tests
pin the boundary that fixes it: a fixture may exercise the engine, and it may
never appear as current Logistics intelligence.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from analysis.provenance import (  # noqa: E402
    CURRENT_PUBLICATION,
    FIXTURE_ORIGINS,
    HISTORICAL_VALIDATION,
    LIVE_FRESHNESS_STATUSES,
    SYNTHETIC_SOURCE_ID,
    TECHNICAL_DEMO,
    effective_source_id,
    fixture_freshness_status,
    is_fixture,
    provenance_problems,
    qualifies_for_current_publication,
    record_intended_source_id,
    record_origin,
    record_source_id,
)
from scripts.build_dashboard import build_payloads  # noqa: E402
from scripts.validate import source_contract_checks  # noqa: E402

PUBLIC = ROOT / "dashboard" / "public"
OBSERVATION_FAMILIES = (
    "indicator_observations",
    "trade_observations",
    "port_observations",
    "cost_observations",
)


def _load(relative: str):
    return json.loads((ROOT / relative).read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def payloads():
    return build_payloads()


@pytest.fixture(scope="module")
def registry():
    return yaml.safe_load((ROOT / "config/sources.yaml").read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def observations():
    return {
        family: _load(f"data/observations/{family}.json")["records"]
        for family in OBSERVATION_FAMILIES
    }


# ---------------------------------------------------------------------------
# §1 / §6: every record says what it is and where it came from
# ---------------------------------------------------------------------------


def test_every_observation_declares_a_recognised_origin(observations):
    for family, records in observations.items():
        for record in records:
            origin = record_origin(record)
            assert origin is not None, f"{family}: a record carries no evidence_origin"
            assert not provenance_problems(record, label=family)


def test_the_whole_observation_set_is_currently_fixture_backed(observations):
    """Stated as a test so the day a real source is enabled, this fails and
    forces every current-publication expectation below to be revisited."""
    origins = {record_origin(record) for records in observations.values() for record in records}
    assert origins <= FIXTURE_ORIGINS
    assert not any(
        qualifies_for_current_publication(record_origin(record))
        for records in observations.values()
        for record in records
    )


def test_no_fixture_is_attributed_to_a_real_publisher(observations):
    for family, records in observations.items():
        for record in records:
            if not is_fixture(record_origin(record)):
                continue
            assert record_source_id(record) == SYNTHETIC_SOURCE_ID, family
            assert record_intended_source_id(record), family


def test_no_fixture_carries_a_retrieval_timestamp(observations):
    for records in observations.values():
        for record in records:
            provenance = record["provenance"]
            assert provenance["retrieval_status"] == "not_retrieved"
            assert provenance["retrieved_at"] is None
            assert provenance["fixture_created_at"]


def test_every_intended_source_is_a_real_registry_entry(observations, registry):
    registry_ids = {source["id"] for source in registry["sources"]}
    for records in observations.values():
        for record in records:
            intended = record_intended_source_id(record)
            if intended:
                assert intended in registry_ids, intended


#: The corrected series-to-source map. WO-010 attributed the freight benchmark
#: and Brent to the fuel publisher, and FX and LSCI to the supply-chain index,
#: because the mapping lived in a hard-coded table beside the series names
#: rather than in each record's provenance.
EXPECTED_INTENDED_SOURCE = {
    "usd_thb_reference_rate": "BOT_FX",
    "thailand_lsci": "UNCTAD_MARITIME",
    "gscpi_index": "GSCPI",
    "brent_crude_price": "WB_COMMODITY",
    "thailand_diesel_retail_price": "EPPO_FUEL",
    "container_freight_benchmark": "FBX_PUBLIC",
    "thailand_port_calls": "IMF_PORTWATCH",
    "laem_chabang_container_throughput": "PAT_STATISTICS",
    "bangkok_port_container_throughput": "PAT_STATISTICS",
}

FORBIDDEN_MAPPINGS = {
    ("container_freight_benchmark", "EPPO_FUEL"),
    ("brent_crude_price", "EPPO_FUEL"),
    ("usd_thb_reference_rate", "GSCPI"),
    ("thailand_lsci", "GSCPI"),
    ("laem_chabang_container_throughput", "IMF_PORTWATCH"),
    ("bangkok_port_container_throughput", "IMF_PORTWATCH"),
}


@pytest.mark.parametrize("series_id,expected", sorted(EXPECTED_INTENDED_SOURCE.items()))
def test_each_series_stands_in_for_the_right_production_candidate(
    observations, series_id, expected
):
    records = [
        record
        for family in OBSERVATION_FAMILIES
        for record in observations[family]
        if (record.get("series_id") or record.get("indicator_id")) == series_id
    ]
    assert records, series_id
    assert {record_intended_source_id(record) for record in records} == {expected}


def test_trade_series_stand_in_for_thai_customs(observations):
    trade = observations["trade_observations"]
    assert trade
    assert {record_intended_source_id(record) for record in trade} == {"TH_CUSTOMS"}


@pytest.mark.parametrize("series_id,forbidden", sorted(FORBIDDEN_MAPPINGS))
def test_the_wo_010_mis_attributions_are_gone(observations, series_id, forbidden):
    """Each pair here is a mapping WO-010 actually made, or one the Work Order
    names as forbidden. Official TEU throughput in particular is not a
    PortWatch estimate and must not be attributed to one."""
    records = [
        record
        for family in OBSERVATION_FAMILIES
        for record in observations[family]
        if (record.get("series_id") or record.get("indicator_id")) == series_id
    ]
    assert records, series_id
    assert forbidden not in {record_intended_source_id(record) for record in records}


def test_effective_source_resolves_a_fixture_to_its_production_candidate(observations):
    record = observations["cost_observations"][0]
    assert record_source_id(record) == SYNTHETIC_SOURCE_ID
    assert effective_source_id(record) == record_intended_source_id(record)


def test_the_dashboard_derives_source_identity_from_provenance_not_a_lookup_table():
    """The hard-coded ``_SOURCE_BY_SERIES`` table is what let a series name and
    a publisher drift apart. It must not come back."""
    source = (ROOT / "scripts" / "build_dashboard.py").read_text(encoding="utf-8")
    assert "_SOURCE_BY_SERIES" not in source


# ---------------------------------------------------------------------------
# §7: the freight benchmark has a real disposition
# ---------------------------------------------------------------------------


def test_a_freight_benchmark_candidate_exists_and_is_not_the_fuel_publisher(registry):
    sources = {source["id"]: source for source in registry["sources"]}
    assert "FBX_PUBLIC" in sources
    benchmark = sources["FBX_PUBLIC"]
    assert benchmark["enabled"] is False
    assert benchmark["enablement"]["blockers"]
    roles = benchmark["qualification"]["logistics_role"]
    assert "freight_market_benchmark_or_proxy" in roles
    assert (
        "freight_market_benchmark_or_proxy"
        not in (sources["EPPO_FUEL"]["qualification"]["logistics_role"])
    )


def test_the_freight_benchmark_never_claims_to_be_a_thailand_rate(payloads):
    series = [
        item
        for item in payloads["cost.json"]["cost_series"]
        if item["series_id"] == "container_freight_benchmark"
    ]
    assert series
    assert series[0]["quotation_claim"] == "not_a_quotation"
    assert series[0]["benchmark_class"] != "actual_quotation"
    assert series[0]["applies_to_thailand"] != "direct"


# ---------------------------------------------------------------------------
# §8: the enablement gate
# ---------------------------------------------------------------------------


def test_no_source_is_enabled(registry):
    assert [source["id"] for source in registry["sources"] if source["enabled"]] == []


def test_tmd_and_gdacs_remain_disabled(registry):
    sources = {source["id"]: source for source in registry["sources"]}
    for source_id in ("TMD_CAP", "GDACS"):
        assert source_id in sources
        assert sources[source_id]["enabled"] is False


def _enabled_candidate(**qualification_overrides):
    """A source that would pass every gate, for one-field negative tests."""
    return {
        "version": "0.8",
        "last_reviewed_at": "2026-07-24",
        "policy": "free_sources_only",
        "sources": [
            {
                "id": "CANDIDATE",
                "name": "Candidate",
                "owner": "Someone",
                "source_class": "official",
                "landing_url": "https://example.org",
                "endpoint": "https://example.org/data.csv",
                "access_method": "http_get",
                "format": "csv",
                "machine_readable_status": "verified",
                "licence_status": "reviewed",
                "enabled": True,
                "required_for_publication": False,
                "known_limitations": ["x"],
                "qualification": {
                    "access_cost": "free",
                    "paywall_status": "none",
                    "reuse_status": "permitted_with_attribution",
                    "redistribution_status": "derived_only",
                    "prototype_eligibility": "eligible",
                    "observed_freshness": "2026-07-20",
                    "publication_cadence": "monthly",
                    "logistics_role": ["thailand_trade_flow"],
                    **qualification_overrides,
                },
                "enablement": {
                    "live_validation_status": "completed",
                    "live_validation_reference": "docs/source_enablement_decisions.md",
                    "fixture_test_exists": True,
                    "fixture_test_reference": "tests/test_csv_series_adapter.py",
                    "parser_fails_closed": True,
                    "response_bounded": True,
                    "schedule_justified": True,
                    "public_repository_safe": True,
                    "blockers": [],
                },
            }
        ],
    }


def test_the_gate_accepts_a_fully_qualified_candidate():
    assert source_contract_checks(_enabled_candidate()) == []


@pytest.mark.parametrize(
    "override,expected",
    [
        ({"access_cost": "paid"}, "free-only policy"),
        ({"access_cost": "unknown"}, "free or free-with-registration"),
        ({"paywall_status": "full"}, "fully paywalled"),
        ({"reuse_status": "unknown"}, "reviewed reuse position"),
        ({"reuse_status": "restricted"}, "reviewed reuse position"),
        ({"redistribution_status": "prohibited"}, "redistribution"),
        ({"prototype_eligibility": "conditional"}, "prototype_eligibility"),
        ({"observed_freshness": None}, "independently observed"),
        ({"publication_cadence": None}, "cadence"),
    ],
)
def test_a_single_unmet_qualification_gate_blocks_enablement(override, expected):
    problems = source_contract_checks(_enabled_candidate(**override))
    assert any(expected in problem for problem in problems), problems


@pytest.mark.parametrize(
    "override,expected",
    [
        ({"blockers": ["endpoint unverified"]}, "unresolved enablement"),
        ({"fixture_test_exists": False}, "fixture test"),
        ({"fixture_test_reference": None}, "fixture test reference"),
        ({"live_validation_status": "not_required"}, "genuinely manual"),
        ({"live_validation_status": "pending"}, "controlled live validation"),
        ({"live_validation_reference": None}, "evidence reference"),
        ({"parser_fails_closed": False}, "fail-closed parser"),
        ({"response_bounded": False}, "bounded response"),
        ({"schedule_justified": False}, "justified collection schedule"),
        ({"public_repository_safe": False}, "public repository"),
    ],
)
def test_a_single_unmet_enablement_gate_blocks_enablement(override, expected):
    registry = _enabled_candidate()
    registry["sources"][0]["enablement"].update(override)
    problems = source_contract_checks(registry)
    assert any(expected in problem for problem in problems), problems


def test_not_required_live_validation_is_allowed_for_a_manual_contract():
    registry = _enabled_candidate()
    registry["sources"][0]["access_method"] = "manual"
    registry["sources"][0]["enablement"]["live_validation_status"] = "not_required"
    registry["sources"][0]["enablement"]["live_validation_reference"] = None
    assert source_contract_checks(registry) == []


# ---------------------------------------------------------------------------
# §9: fixture freshness is disjoint from real-world freshness
# ---------------------------------------------------------------------------


def test_a_fixture_never_receives_a_real_world_freshness_label():
    for origin in FIXTURE_ORIGINS:
        assert fixture_freshness_status(origin) not in LIVE_FRESHNESS_STATUSES
    assert fixture_freshness_status("synthetic_test_fixture") == "fixture_not_live"
    assert fixture_freshness_status("historical_validation_fixture") == "historical_validation"
    assert fixture_freshness_status("live_retrieved") == "not_applicable"


def test_every_demo_series_reports_fixture_freshness(payloads):
    series = [
        *payloads["cost.json"]["cost_series"],
        payloads["cost.json"]["fx"],
        *payloads["ocean.json"]["demo_port_series"],
        *(flow for lane in payloads["trade.json"]["lane_flows"] for flow in lane["flows"]),
    ]
    assert series
    for item in series:
        assert item["freshness"]["status"] == "fixture_not_live", item.get("series_id")


def test_no_current_domain_assessment_claims_real_world_freshness(payloads):
    for lane in payloads["ocean.json"]["lanes"]:
        for domain in lane["assessment"]["domain_assessments"]:
            assert domain["freshness"]["status"] == "no_data"


# ---------------------------------------------------------------------------
# §1 / §10: the current view holds nothing fixture-derived
# ---------------------------------------------------------------------------


def test_the_current_thailand_view_is_insufficient_across_the_board(payloads):
    situation = payloads["thailand_situation.json"]
    assert situation["dataset"] == CURRENT_PUBLICATION
    assert situation["overall_direction"] == "insufficient_evidence"
    assert situation["evidence_coverage"] == "insufficient"
    assert situation["active_verified_events"] == []
    assert situation["lanes_requiring_attention"] == []
    assert situation["qualified_observation_count"] == 0
    assert situation["qualified_event_count"] == 0


def test_no_lane_is_raised_above_routine_in_the_current_view(payloads):
    for lane in payloads["ocean.json"]["lanes"]:
        assessment = lane["assessment"]
        assert assessment["dataset"] == CURRENT_PUBLICATION
        assert assessment["attention_level"] == "insufficient_evidence"
        assert assessment["overall_direction"] == "insufficient_evidence"
        assert assessment["active_event_ids"] == []


def test_the_demo_assessments_still_exercise_the_engine(payloads):
    """The demonstration must remain a real demonstration: if every demo lane
    also came out 'insufficient', the separation would be untested."""
    demo = [lane["demo_assessment"] for lane in payloads["ocean.json"]["lanes"]]
    assert all(item is not None for item in demo)
    assert all(item["dataset"] == TECHNICAL_DEMO for item in demo)
    assert any(item["attention_level"] in {"watch", "elevated"} for item in demo)


def test_no_chokepoint_is_labelled_as_having_an_active_notice(payloads):
    for lane in payloads["ocean.json"]["lanes"]:
        for exposure in lane["assessment"]["chokepoint_exposure"]:
            assert exposure["status"] != "official_notice_active"
    assert payloads["ocean.json"]["current_operational_notices"] == []
    assert payloads["ocean.json"]["current_capacity_and_service_evidence"] == []


def test_no_current_event_is_published(payloads):
    events = payloads["events.json"]
    assert events["dataset"] == CURRENT_PUBLICATION
    assert events["current_direct_operational_events"] == []
    assert events["current_external_drivers"] == []
    # The historical cases are still there, in their own labelled group.
    assert events["demo_direct_operational_events"]


def test_every_historical_event_carries_its_assessment_cutoff(payloads):
    demo = payloads["events.json"]["demo_direct_operational_events"]
    assert demo
    for event in demo:
        assert event["dataset"] == HISTORICAL_VALIDATION
        assert event["assessment_cutoff"], event["event_id"]
        assert event["case_id"], event["event_id"]
        assert event["active_as_of"] is None


def test_current_scenarios_state_only_what_coverage_is_missing(payloads):
    outlooks = payloads["ai_outlook.json"]["current_outlooks"]
    assert len(outlooks) == 11
    for entry in outlooks:
        assert entry["attention_level"] == "insufficient_evidence"
        base = entry["scenarios"]["base_case"]
        assert base["trigger_conditions"], entry["lane_id"]
        assert base["data_gaps"], entry["lane_id"]


def test_evidence_records_separate_expected_strength_from_verified_strength(payloads):
    items = [
        item
        for event in payloads["events.json"]["demo_direct_operational_events"]
        for item in event["evidence"]
    ]
    assert items
    for item in items:
        assert item["strength_basis"] == "expected_at_cutoff"
        assert item["retrieval_status"] == "not_retrieved"
        assert item["retrieved_at"] is None
        assert item["intended_source_id"]


# ---------------------------------------------------------------------------
# §10: the label is on every panel, not only the page banner
# ---------------------------------------------------------------------------


def test_the_page_declares_a_current_and_a_demonstration_region_for_each_topic():
    html = (PUBLIC / "index.html").read_text(encoding="utf-8")
    for current_id, demo_id in (
        ("situation-cost-current", "situation-cost-table"),
        ("current-notice-statement", "notices"),
        ("trade-current", "trade-demo-label"),
        ("cost-current", "cost-demo-label"),
        ("events-current-statement", "events-demo-label"),
        ("current-outlooks", "outlook-demo-label"),
    ):
        assert f'id="{current_id}"' in html, current_id
        assert f'id="{demo_id}"' in html, demo_id


def test_every_demonstration_heading_carries_its_own_marker():
    """A page-level banner is not enough: a reader who deep-links to a section
    or prints one panel must still see that it is a demonstration."""
    html = (PUBLIC / "index.html").read_text(encoding="utf-8")
    headings = re.findall(r'<h3 class="demo-heading">(.*?)</h3>', html, re.S)
    assert len(headings) >= 6
    for heading in headings:
        assert "pill-demo" in heading, heading


def test_the_renderer_labels_each_fixture_backed_panel_individually():
    script = (PUBLIC / "assets" / "app.js").read_text(encoding="utf-8")
    assert "DEMO_LABEL" in script
    assert "demoTag(" in script
    # Series blocks, event cards, outlook blocks and the in-card lane panel.
    assert script.count("data-demo-label") >= 4
    assert "demo-panel" in script


def test_fixture_freshness_statuses_are_styled_as_demonstration_not_as_fresh():
    script = (PUBLIC / "assets" / "app.js").read_text(encoding="utf-8")
    pills = script.split("var FRESHNESS_PILL", 1)[1].split("};", 1)[0]
    for status in ("fixture_not_live", "historical_validation", "not_applicable"):
        assert status in pills, status
    assert "fixture_not_live: 'pill-demo'" in pills
