"""Series catalogue: which CSV column becomes which observation record.

This is the metadata that keeps ``csv_series.py`` a single generic parser
instead of one bespoke parser per publisher. Each entry states the series'
identity, its unit, the geography and lane it applies to, and -- critically
for the cost series -- what kind of number it is, so that a route proxy can
never be rendered as a Thailand shipment quotation.

Every spec here is currently bound to a **synthetic test fixture**. The
``evidence_class`` on each one says so, and it propagates into every derived
record, indicator and Dashboard panel.
"""

from __future__ import annotations

from .adapters.csv_series import CsvSeriesContract, SeriesSpec

#: Evidence class carried by every record built from the WO-010 fixtures.
FIXTURE_CLASS = "synthetic_test_fixture"

_FIXTURE_LIMITATION = (
    "Generated by scripts/generate_synthetic_fixtures.py. This value is a synthetic "
    "test fixture, not a published statistic, and must not be read as an observation "
    "of the real world."
)

#: Lane groups, paired with the fixture column suffix and the partner label
#: the trade observation should carry.
_LANE_COLUMNS = (
    ("LANE-OCEAN-TH-EASIA-CN", "easia_cn", "Mainland China and Hong Kong", "CN"),
    ("LANE-OCEAN-TH-JPKR", "jpkr", "Japan and Korea", None),
    ("LANE-OCEAN-TH-ASEAN-SG", "asean_sg", "ASEAN and Singapore transshipment", None),
    ("LANE-OCEAN-TH-SASIA", "sasia", "South Asia", None),
    ("LANE-OCEAN-TH-MEGULF", "megulf", "Middle East and Gulf", None),
    ("LANE-OCEAN-TH-NEUR", "neur", "Northern Europe", None),
    ("LANE-OCEAN-TH-MED", "med", "Mediterranean", None),
    ("LANE-OCEAN-TH-USWC", "uswc", "United States West Coast", None),
    ("LANE-OCEAN-TH-USEC", "usec", "United States East and Gulf Coast", None),
    ("LANE-OCEAN-TH-OCEANIA", "oceania", "Australia and New Zealand", None),
    ("LANE-OCEAN-TH-DOMESTIC", "domestic", "Thailand domestic and inland connection", "TH"),
)


def _trade_specs() -> tuple[SeriesSpec, ...]:
    specs: list[SeriesSpec] = []
    for lane_id, slug, label, partner_country in _LANE_COLUMNS:
        for direction in ("export", "import"):
            specs.append(
                SeriesSpec(
                    series_id=f"th_{direction}_value_{slug}",
                    family="trade",
                    value_column=f"{direction}_value_{slug}",
                    unit="THB_million",
                    currency="THB",
                    period_type="month",
                    evidence_class=FIXTURE_CLASS,
                    geography_id="GEO-CTY-TH",
                    country_id="TH",
                    # Published customs totals are all-mode. Tagging them
                    # 'sea' would assert a mode split the source does not
                    # provide, so they stay mode-neutral and the Ocean module
                    # reads them as lane context rather than as ocean volume.
                    transport_mode="not_applicable",
                    lane_id=lane_id,
                    known_limitations=(
                        _FIXTURE_LIMITATION,
                        "Trade value is an all-mode total. It is not an ocean-only figure "
                        "and must not be presented as ocean freight volume.",
                    ),
                    attributes={
                        "series_id": f"th_{direction}_value_{slug}",
                        "flow_direction": direction,
                        "reporter_country_id": "TH",
                        "partner_country_id": partner_country,
                        "partner_scope": "country" if partner_country else "lane_group",
                        "partner_label": label,
                        "commodity_scope": "all_commodities",
                        "measure": "value",
                    },
                )
            )
    return tuple(specs)


TRADE_CONTRACT = CsvSeriesContract(
    source_id="TH_CUSTOMS",
    parser_version="thai_customs_v1",
    period_column="period",
    published_at_column="published_at",
    series=_trade_specs(),
)


PORT_CONTRACT = CsvSeriesContract(
    source_id="IMF_PORTWATCH",
    parser_version="portwatch_v1",
    period_column="period",
    published_at_column="published_at",
    series=(
        SeriesSpec(
            series_id="laem_chabang_container_throughput",
            family="port",
            value_column="laem_chabang_teu",
            unit="teu",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-CTY-TH",
            country_id="TH",
            transport_mode="sea",
            node_id="NODE-THLCH",
            lane_id="LANE-OCEAN-TH-DOMESTIC",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "Throughput measures how much cargo moved. It can never on its own "
                "establish congestion, waiting time or berth delay.",
            ),
            attributes={
                "series_id": "laem_chabang_container_throughput",
                "metric": "container_throughput",
                "operational_interpretation": "volume_only",
                "resolution": "node",
            },
        ),
        SeriesSpec(
            series_id="bangkok_port_container_throughput",
            family="port",
            value_column="bangkok_port_teu",
            unit="teu",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-CTY-TH",
            country_id="TH",
            transport_mode="sea",
            node_id="NODE-THBKK",
            lane_id="LANE-OCEAN-TH-DOMESTIC",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "Throughput measures how much cargo moved and is not a congestion measure.",
            ),
            attributes={
                "series_id": "bangkok_port_container_throughput",
                "metric": "container_throughput",
                "operational_interpretation": "volume_only",
                "resolution": "node",
            },
        ),
        SeriesSpec(
            series_id="thailand_port_calls",
            family="port",
            value_column="thailand_port_calls",
            unit="port_calls",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-CTY-TH",
            country_id="TH",
            transport_mode="sea",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "A port-call count is a model-derived activity estimate, not an official "
                "port statistic, and is a volume measure only.",
            ),
            attributes={
                "series_id": "thailand_port_calls",
                "metric": "vessel_calls",
                "operational_interpretation": "volume_only",
                "resolution": "country",
            },
        ),
    ),
)


COST_CONTRACT = CsvSeriesContract(
    source_id="EPPO_FUEL",
    parser_version="eppo_fuel_v1",
    period_column="period",
    published_at_column="published_at",
    series=(
        SeriesSpec(
            series_id="thailand_diesel_retail_price",
            family="cost",
            value_column="thailand_diesel_retail",
            unit="THB_per_litre",
            currency="THB",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-CTY-TH",
            country_id="TH",
            transport_mode="not_applicable",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "A retail pump price is domestic cost context. It is not a bunker fuel "
                "price and not a cost any carrier actually pays for ocean freight.",
            ),
            attributes={
                "series_id": "thailand_diesel_retail_price",
                "cost_family": "retail_fuel",
                "benchmark_class": "published_official_price",
                "quotation_claim": "not_a_quotation",
                "route_scope": None,
                "applies_to_thailand": "measured",
            },
        ),
        SeriesSpec(
            series_id="brent_crude_price",
            family="cost",
            value_column="brent_crude",
            unit="USD_per_barrel",
            currency="USD",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-WORLD",
            transport_mode="not_applicable",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "A crude benchmark is upstream energy context. The pass-through to bunker "
                "fuel and then to freight cost is neither immediate nor proportional.",
            ),
            attributes={
                "series_id": "brent_crude_price",
                "cost_family": "crude_energy",
                "benchmark_class": "market_benchmark",
                "quotation_claim": "not_a_quotation",
                "route_scope": None,
                "applies_to_thailand": "directional_context_only",
            },
        ),
        SeriesSpec(
            series_id="container_freight_benchmark",
            family="cost",
            value_column="container_freight_benchmark",
            unit="index_points",
            currency="USD",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-WORLD",
            transport_mode="sea",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "This is a market benchmark for a third route, used only as a directional "
                "indicator. It is not a Thailand shipment quotation, not a Thailand "
                "average, and not a rate any shipper was charged.",
                "No qualified dataset covering Thailand-origin freight rates exists in this "
                "registry, so no Thailand freight average is published anywhere in the "
                "platform.",
            ),
            attributes={
                "series_id": "container_freight_benchmark",
                "cost_family": "container_freight",
                "benchmark_class": "route_proxy",
                "quotation_claim": "not_a_quotation",
                "route_scope": "Composite east-west mainlane benchmark, not a Thailand route",
                "applies_to_thailand": "directional_context_only",
            },
        ),
    ),
)


INDICATOR_CONTRACT = CsvSeriesContract(
    source_id="GSCPI",
    parser_version="gscpi_v1",
    period_column="period",
    published_at_column="published_at",
    series=(
        SeriesSpec(
            series_id="usd_thb_reference_rate",
            family="indicator",
            value_column="usd_thb_rate",
            unit="THB_per_USD",
            currency="THB",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-CTY-TH",
            country_id="TH",
            transport_mode="not_applicable",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "A reference rate is cost context. It does not establish a change in any "
                "cost actually paid.",
            ),
            attributes={
                "indicator_id": "usd_thb_reference_rate",
                "indicator_name": "USD/THB reference exchange rate",
                "indicator_family": "fx",
                "baseline_definition": None,
            },
        ),
        SeriesSpec(
            series_id="gscpi_index",
            family="indicator",
            value_column="gscpi_index",
            unit="index_points",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-WORLD",
            transport_mode="multimodal",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "A global index cannot establish a Thailand-specific or lane-specific "
                "conclusion on its own.",
            ),
            attributes={
                "indicator_id": "gscpi_index",
                "indicator_name": "Global Supply Chain Pressure Index",
                "indicator_family": "global_baseline",
                "baseline_definition": (
                    "Zero, defined by the publisher as the series average expressed in "
                    "standard deviations. Deviation is publishable for this series because "
                    "the baseline is explicit and published."
                ),
            },
        ),
        SeriesSpec(
            series_id="thailand_lsci",
            family="indicator",
            value_column="thailand_lsci",
            unit="index_points",
            period_type="month",
            evidence_class=FIXTURE_CLASS,
            geography_id="GEO-CTY-TH",
            country_id="TH",
            transport_mode="sea",
            known_limitations=(
                _FIXTURE_LIMITATION,
                "A connectivity index is a structural measure of liner network coverage. "
                "It is not an operational condition and cannot detect an event.",
            ),
            attributes={
                "indicator_id": "thailand_lsci",
                "indicator_name": "Thailand liner shipping connectivity index",
                "indicator_family": "connectivity",
                "baseline_definition": None,
            },
        ),
    ),
)


#: Fixture file -> parse contract. The ingest script walks this mapping, so
#: adding a source is a catalogue change rather than a code change.
FIXTURE_CONTRACTS = {
    "thailand_trade_by_lane_monthly.csv": TRADE_CONTRACT,
    "thailand_port_activity_monthly.csv": PORT_CONTRACT,
    "cost_and_freight_monthly.csv": COST_CONTRACT,
    "baseline_indicators_monthly.csv": INDICATOR_CONTRACT,
}
